### PR TITLE
Updates to align with basic exp template v5.0.3

### PR DESCRIPTION
**Pull request by jessestorbeck**
I didn't think to make this change before because the new version of the basic template is also still on a jsPsych 6 stylesheet. I plan to change that one too so that experiments people develop with jsPsych match up aesthetically when they paste their code into their Pushkin experiment.

### CODE REVIEW

**Review by jkhartshorne — DISMISSED** [review]
Seems to work.

**Comment by jkhartshorne** [comment]
@jessestorbeck -- I've approved this. But since it involves a lot of changes I just made, I'd appreciate you checking it out, too, before merging.

**Comment by jkhartshorne** [comment]
@ellissc -- would be awesome if you could check this locally, too.

**Comment by jkhartshorne** [comment]
@ayang21 -- please also check

**Comment by jessestorbeck** [comment]
@ayang21 @ellissc -- This one can be tested now along with https://github.com/pushkin-consortium/pushkin-exptemplates-grammatical/pull/4 (you could add a few of each to the same site to play with the config options). Docs are [here](https://languagelearninglab.gitbook.io/pushkin/advanced/modifying-experiment-templates/lexical-decision-template).

**Review by ayang21 — APPROVED** [review]

**Pull request merged**
