### PR TITLE
Jest testing code

### PR DESCRIPTION
**Pull request by Weiiirrr**
Please review the Jest testing code.

### CODE REVIEW

**Comment by jkhartshorne** [comment]
@hzeng2 @jessestorbeck -- reminding you of this review request. You should be able to test now.

**Review by hzeng2 — APPROVED** [review]
All tests passed, by running `yarn add -D jest-environment-jsdom` first.

**Comment by jkhartshorne** [comment]
@Weiiirrr -- you should be able to add jest-environment-jsdom to the repo, following your instructions. Can you please make that update, commit, and push before we merge? Thanks!

**Comment by jkhartshorne** [comment]
@Weiiirrr -- alternatively, see https://github.com/pushkin-consortium/pushkin-exptemplates-reading/pull/2#pullrequestreview-1494349562

**Comment by jkhartshorne** [comment]
We're going to leave testing for later, as part of the migration to the newer react-redux, react-router, and to Vite.

**Pull request closed without merging**
